#+TITLE: Hoovy Home

* Init
#+BEGIN_SRC emacs-lisp
(defgroup hoovy nil
  "Hoovy Customization Group"
  :link '(custom-manual "(hoovy)Top"))

(defcustom hoovy-root "~/hoovy"
  "Root Path"
  :type 'directory
  :group 'hoovy)

(defcustom hoovy-apps
  '(("Krita" . "krita")
    ("Hexchat" . "hexchat")
    ("DOOM (Zandronum)" . "~/Downloads/zandronum")
    ("OpenToonz" . "opentoonz")
    ("Firefox" . "/opt/firefox/firefox"))
  "List of Applications"
  :type '(alist :key-type string :value-type file)
  :group 'hoovy)

#+END_SRC

* Start Page
#+BEGIN_SRC emacs-lisp
(defun hoovy-spawn-app (name file)
  (let ((buf (concat "*" name "*")))
    (async-shell-command file buf buf)))

(require 'widget)
(eval-when-compile (require 'wid-edit))

(defun hoovy-all-apps ()
  "add earmuffs to hoovy-apps"
  (mapcar (lambda (x) `(,(concat "*" (car x) "*") . ,(cdr x)))
	   hoovy-apps))

;;
;; TODO: do initial-buffer-choice setup 
;;
(defun hoovy-welcome ()
  "Hoovy Welcome Page"
  (interactive)
  (switch-to-buffer "Hoovy")
  (kill-all-local-variables)
  ;;(make-local-variable 'asdfasdf)
  (let ((inhibit-read-only t))
    (erase-buffer))
  (remove-overlays)
  (widget-insert "Welcome to Hoovy Studio\n\n")
  (dolist (a (hoovy-all-apps))
    (widget-create 'push-button
		   :notify (lambda (&rest ignore)
			     (async-shell-command (cdr a)
						  (car a) (car a)))
		   (car a)))
  (use-local-map widget-keymap)
  (widget-setup))
#+END_SRC

[[elisp:(hoovy-spawn-app "Krita" "~/Downloads/krita-3.3.1-x86_64.appimage")][Krita]]
[[elisp:(hoovy-spawn-app "OpenToolz" "opentoolz")][OpenToolz]]
[[elisp:(hoovy-spawn-app "Blender" "~/Downloads/blender-2.78c-linux-glibc219-x86_64/blender")][Blender]]


* Org Mode
#+BEGIN_SRC emacs-lisp

(defun hoovy-www () (concat hoovy-root "/www/"))
(setq org-default-notes-file (concat hoovy-root "/notes.org"))

(define-key global-map (kbd "C-c c") 'org-capture)

;; (defun hv-make-notes (&optional name)
;;   `(,(concat name "-notes")
;;    :base-directory ,(concat hv-root "/" name "/org")
;;    :base-extension "org"
;;    :publishing-function org-publish-org-to-html
;;    :publishing-directory ,(concat hv-www "/dev/" name)
;;    :auto-sitemap t
;;    :sitemap-title "/Site Map/"
;;    :sitemap-alphabetically nil
;;    :recursive t
;;    :style-include-default t
;;    :headline-levels 4
;;    :auto-preamble t))

;; (defun hv-make-static (&optional name)
;;   `(,(concat name "-static")
;;     :base-directory ,(concat hv-root "/" name "/org")
;;     :base-extension "css\\|js\\|png\\|gif\\|pdf\\|mp3\\|ogg\\|svg"
;;     :publishing-function org-publish-attachment
;;     :publishing-directory ,(concat hv-www "/dev/" name)
;;     :recursive t))

;; (setq org-capture-templates
;;       '(("t" "Todo" entry (file+headline "" "Tasks")
;;          "* TODO %?\n  %i\n  %a")
;;         ("j" "Journal" entry (file+datetree "")
;;          "* %?\nEntered on %U\n  %i\n  %a")))

(setq org-publish-project-alist
      `(("hoovy"
	 :base-directory ,hoovy-root
	 :recursive t
	 :publishing-directory ,(hoovy-www)
	 :publishing-function org-html-publish-to-html
	 :html-head-extra ""
	 :components ())))

(org-display-inline-images t t)
(setq org-edit-src-content-indentation 0
      org-src-tab-acts-natively t
      org-src-fontify-natively t
      org-confirm-babel-evaluate nil
      org-support-shift-select 'always)

(org-babel-do-load-languages 'org-babel-load-languages
    '((emacs-lisp . t)
      (shell . t)
	  (ocaml . t)
	  (lisp . t)))

#+END_SRC

* Projects
** <Nova>

Common Lisp game development and animation and music production tools.

** Gamelike

Roguelike game inspired by Ragnarok Online and Shiren: The Wanderer.

** Novapilot

2D game inspired by Bangai-O
Built in level editor

** Monsterpiece

2D game inspired by Mario Bros and Smash Bros and Metroid and Castlevania.
Single-room monster breed/fight/collect maze platform action.

* Cancelled Projects

** Mini Macs (hu-macs)
[[file:ectron.el][Emacs Electron]]
[[file:emacsript.el][Emacs ParenScript]]

** Erl-Dev
Erlang multiplayer game server. Supported IRC and other pieces. [[http://github.com/humasect/erl-dev]]

** Nova
Haskell realtime 2D graphics and media engine. [[http://github.com/humasect/Nova]]
Website with documentation and tutorial is missing. ( [[http://hoovy.org]] )

** The Middle
Objective-C library for iOS and macOS for high performance turtle-style graphics and game development for Emacs and Xcode.

** HaskellPlugin
http://github.com/humasect/HaskellPlugin
Plugin for Haskell for old version of Xcode.

* Programming

** Update Emacs
#+BEGIN_SRC shell :exports code
cd ~/Downloads/emacs
git fetch
./configure --with-modules --with-x-toolkit=lucid
make
#+END_SRC

** git status
#+BEGIN_SRC shell :exports code
git status
#+END_SRC

** dropbox
#+BEGIN_SRC shell :exports code
dropbox start && dropbox status
#+END_SRC

* Communications

[[irc:/irc.freenode.net/#emacs][#emacs on freenode]]

* News
| [[https://news.ycombinator.com/][Hacker News]] | [[http://rockpapershotgun.com/][Rock Paper Shotgun]] | [[http://sachachua.com/blog/category/emacs/][Sacha Chua Emacs Blog]] |


