#+TITLE: Human Technology

* Computer Programming Language
** basic unit: atom
** object: number
** object: list
** object: person
*** memory
*** mailbox
*** actions
*** passions
** object: computer
*** 

** Cell


* Symmetry
sit straight

* Body and Mind
body moves, mind stays still.

* Technology is Black Magic
we spend our light points to pull something in to our mind in enjoyment or displeasure.

* the internet
we are building this perfect endless artificial heaven and we are trying to upload our best version of ourselves into it, for some kind of immortality, but it is not going to work that way. no one else is watching, its a hellish pit of soul traps. it is best to stay away from investing too much into that place.

* the world
weare not trapped in this place. there is a way out, a way to fix everything. and now we are following it, having gone too far the one way (toward complexity)

* outer space
our scientific idea of space is the externally manifested vaccuous singularity of infinity. it is the center of the world, and shrinking our tech and celebs into it might not exactly help with understanding what is actually going on.

* the earth
it expands outward, as resolution/growth/time increases. gravity is the push from the center. 'dinosaur' bones expand like sponges, the fossiled objects of the dug past.

* the human body
symmetry is very important. so is the belly and the nose and the hands. very important

* the mind
dont lose it. follow the eyes. watch where you put it before it gets too wild.

* acting around other people
dont make so much noise; everyone has to hear it, and it only adds to karmic debt. it is the conflict of bodies trying to occupy the same space. it taxes the system.

* network and processing
please be kind to other users and respect the equal opportunity for processing time. try to keep your personal objects in your awareness, and realise that simplofying our environment can be a great benefit to mental clarity and sense of peace, which is essential for smooth operation.

* scoring
one's rewards and punishments are appropriate to the benefit or disruption to the system as a whole. we can all live together.

* 

