#+TITLE: About Me

* Beginning 2018-10-05
** One
This file is going to be all about myself. Like a journal of sorts.  I've got a lot of things to sort, that is for certain. I will be experimenting with language and various story telling formats possibly, but the main point and purpose of this is Output. I need to figure things out about myself and it has to be linguistic, a physical and tangible activity. More productive and constructive than if it were idle rumination or accidental discovery.
** Two
I can establish a dialog. Invent some characters, imaginate some events and action, intrigue and settings. First i've got to bulid momentum. Find my voice, as they say. I will try to keep it a daily thing, if not more. It also has to be challenging, and hard work. Its all about me so I should never run out of inspiration, being myself all the time as it is - not to say I am arrogant. Far from it, perhaps the opposite; this is also hopefully an activity which could lead to the practical development of a healthy sense of self, which seems to be missing or lacking or traumatized or hiding or an unsolvable mystery...
Don't lose momentum. Keep at it. Text is a fine medium. Lots of room to develop and recover your own style. I really should be programming myself and my environment and not computers and games. Working with natural spoken native language is how we do that. Happiness is a focus. Lack of confusion, enhancement of clarity. Work out my karmic debt and hopefully inspire others.
** Three
There is always something to say. Make it hard work. We can worry less about capitalization and punctuation but start simple. I guess I treat people as if they are computer language compilers? Write some code, submit to compilation, process errors or warnings, update code... I don't feel that i think of them any less human. I just love everyone so much, it is better for me to get a healthy amount of solitude. So, when I say "I", I am likely having a personal though, as if one were murmuring to oneself. And when I say "You", I don't mean >you< the reader except right there, but me myself. I'm talking to myself. So I say "you" like one would do into a mirror or to a video to themselves. When i say "We", i am also still talking to myself, as if in the form of ego-check; to increase esteem or confidence, or to decrease pride or arrogance. Sometimes i say "We" in a general sense meaning us-together as a whole human race. I don't know any reader and I am preoccupied with getting to know myself in the first place. If that is even possible! If it were, perhaps we should be selling it in between slices of bread on the street corners.
* Off the computer 2018-10-06
** One
going to try my best to use the computer as little as possible. Today i wrote out two tehillim (1+2) before any computing. Had a coffee and a cigarette. Stu gave me some, and had already coffee made. I was going to make some and seen that he had already. He may have knocked earlier before i fully awoke to ask me if i wanted to have some coffee. Medley came over, then Ben and Nick showed up. Funny guys, good bros for each other i think. I wish i was more normal or making people laugh or even just a little bit more chill and inspiring, that would be cool. Hopefully some day if given enough time, I could smoothen out my wrinkles so to speak.

** Two
I've picked up the Emacs Lisp project to study some Hebrew stuff, in [ivrit.org].
