#+TITLE: Nova Project

* Nova Computer (NVC)
Experimental Idea
** Terminal
*** Display
 512x512 1bit (262144 pixels, 32kb)

 0,0 is lower left
 511,511 is top right

 8x8 tiles, 64x64 max tiles (or 8x16??)
 
*** Parts
 sound > sample
					> function
 image > pixel

*** Characters
 8x16 8bit (1024 bytes)

 coordinates can be specified as char:
 101 - 3264
 or fine coords:
 1,1 - 32,64

*** Processor
 locally executes instruction codes. (lisp vm)

*** Input
text stream I/O.

** Programming
 - encryption or some smarts to prevent game progress hacking
** Session
 persistent user sessions
** Memory Tree Filesystem
- shared symbols organized as a list of lists.
- symbols can be remote pointers (message passing).
- namespaces (branches) can be associated to and resolved from physical or virtual places.
- real NVC files are virtual. but virtual NVC files are real files...

** Network
- clients use HTTP, JSON API, or Swank.

* Game Engine
** Porting from HS-Nova (Haskell)
- ~/hoovy/nova-ml
- finish porting the "game/system" modules.
** Targets
- Local native
- Web Canvas
- OpenGL?
** Drawing
- using cube tiles, or full geometry in parts but connecting doorways ?
- turtle
- draw, lift pen, stroke, path, bitops, et
- polygon windings?


* The Mech
Called Nova
** the novaphone
 his grand and complicated magical (blessed) organ can travel in the galaxy.
 it is made of junk parts from things given to him. each part has sentimental value. (karma)
 he lands it on a planet , and this is head quarters. he can return here with parts he found,
    new items to mix in the lab, save and heal.
 there is a lot of traveling back to novaphone, many items need to be analyzed
 nova has everything he needs to live a long life of peace inside novaphone.
 how it was created, revealed in pieces during game, of nova's past:
    during a great mission, partners and friends he thought he trusted has turned on him
    so easily. he was left with nothing and stranded in a barren junk planet. he started to build a
    home here, with junk parts. he was later able to make it travel on land, where he found other
    people. he was doing services for the good and not for the bad, helping others -- in this way
    his home became greater exponentially and was able to travel in space soon. when he was
    first abandoned in the barren wasteland area, he spent 3 years and 3 months in solitude.
** the lab
 in the ship there is a lab for making various potions, concotions both bad and good
 here many items are made, like fire attack bombs, regular bombs, even bullets.
 it also works with metal and can make some special parts for upgrades and progress.


* The Pilot
** STORY
 he travels alone in space until the federation sends him a message but they haven't met
   until his help is requested by them. they know of him from his mercenary name, The Whistler.
   they had a hard time to track him down and find him. nova notices the message in a public place
   like a Wanted sign, he decides to set up a safe meeting from a distance to see. never does he
   visit them personally until the relationship between nova and the federation are more secure,
   where both sides have what the other wants; in such a way that either party can abort safely.
   at first they are both afraid of each other; nova doesn't want to get caught or somehow harmed,
   and the federation does not want to be destroyed knowing of nova's past life and reputation.
 he accepts the federation's dire request because he thinks even from his painful and evil past,
	that he can do something right by having an idea that he has a purpose and this is it.
	in the end he realises his chosen peaceful life was the real purpose, where he had everything.

 at first they are good guys with no harm. in the end, they end up being the bad ones, and they
 themselves did not even know it. so through the adventure, nova using his morals finds more and
 more that the federation is indeed the true enemy, not the harmless creatures he is sent to planets
 to either:
 - eradicate those that seem hostile
 - collect for study those that seem harmless/helpful
 - or to change and modify and interrupt those who are neither harmful or helpful.
 so in the end nova finds out the federation is just scared of the 5 planets because they don't
 understand them. nova along the way helps them to get rid of the real enemy, inside themselves

 - takes place on galaxy federation planet or ship run by robots and machine
 ? hero can disengage her suit to zero, for certain areas or environments ?
	then, when engaged or spotted by robot or camera detection, robots come and
	samus must change into suit... will give a great sense of human fragility.
 - zen chozo masters
 - story telling but not like fusion, instead like castlevania, but computers
- hero is a wandering alchemist.
- he has a mechship.
- he is known around the galaxy for helping others.
- his dressing is in tattered robes
- he is always happy, even at very scary and threatening large bosses to hurt him
- he has great knowledge of the 5 elements
- he also has great knowledge of the two opposing forces, light and dark. neither are good or bad.
- he is a retired bounty hunter a long time ago,
- now is in a life of peaceful living and music and helping
  those who he encounters in his passive/reactive travels
** Weapons
 two-handed and one-handed ?
   only sheilds for one handed or no handed ?

 atk speed, atk power
- starting gun is default pistol-like single shot arm cannon
- mid way through game upgrade is rapid fire machine-style shooting with shells.
  this weapon is rapid but overheats.
- green laser that might bounce one time. toothpaste green, bright and
  spilly and splashy and with travel. might push a little, samus and/or enemies.
- actually a railgun, it shoots for 1 second and has 1 second delay. pushback for
  samus prevents her from movement. so it is a precise weapon like sniper.
** Actions
- he throws bombs.
- his potions come in vials to throw or to use on himself
- he collects item in the bag he carries
- E-tank
- missile tank
- electric whip/grapple ?
** GAMEPLAY
 - three skills: beginner, normal, advanced.
 - melee? smash brothers maybe auto, charging into them, kicking them
 - mouse to aim.
 - buttons on keyboard to move left right, down is duck, up is jump
 - button for fire (selected weapon/item) and bombs in morph
 ? there are curving geometry for morph ball requiring acceleration/momentum ?
 - gravity changes in some areas like mario galaxy
 - screen can turn and rotate left and right, and zoom
 - gravity weapons that attract samus to it because of the suit, gravity suit can
     overcome it

** skills
 fire, ice, heal, etc.

** equipment screen
 can equip:
 - body
 - head
 - feet
 - accessory 1
 - accessory 2
 - weapon
 - skill
** status screen
 xp, gold, time, monster count.
 stats are distributed manually among these:

 DEX (attack, defense)
 AGI (dodge, luck)
 CON (hp, mp)
 WIS (Matk, Mdef)

 both equipment and manual stats affect these:
 Attack, Defense, Dodge, luck, Mdef, Matk, health points, magic points, crit.
* Game World
Dharma in a game

** ENVIRONMENT
- space, tech, earthy, cyber
- gears and clockwork!
- the inner architecture of planets.
- geometry able to become destroyed in some areas.
  it should be obvious to the player.
- powerfully atmospheric lighting, like abuse mixed with doom3.
- lots of engines and pipes and gears and machine and pits and mystery spots.
- but not too dark.
- neat doors

** Landmarks
- save station
- shops
- populated areas
- unexplored/dangerous areas
** ENEMIES
 - all are robots.
 - bland colors such as grey, greyish blue, greyish green, brown, etc,
     are defeated with any weapon.
 - strong colors such as green, red, use certain aquired weapons to defeat
 - armor plays similar role with the suit of samus

** the planets
 nova is requested by the federation to be the only one who doesn't fear. and he is known
 for his strong powers that they can only 50% understand with science, enough that they
 are not scared. so he is sent to missions on the planets to help the federation with their goals.

 the future city is the hub planet. it is the start and the end of the journey,
 the center of all 5 main planets, it is floating in space. this is where the federation and
 the population are. in the beginning it is a city, but progressing in the adventure it ends up
 to be a military fortress. nova observes the changes and helps with many of them through
 his missions on the planets.

*** 1 Rupa, the cave planet (yellow, earth, form/matter, mouth?)
	 is where wood bombs are useful.
	 there are insect creatures here.

*** 2 Vedana, the forest planet (green, wood, contact/feeling/sensation, eyes)
	 is where metal bombs are useful.
	 there are plant creatures here.

*** 3 Sanna, the machine planet (white, metal, perception/discrimination/cognition, nose)
	 is where fire bombs are useful.
	 there are cold machines here.

 swap 3 & 4?

*** 4 Sankhara, the ice planet (blue, water, will/volition, ears)
	 is where earth bombs are useful.
	 there are mysterious forces of nature here.

*** 5 Vinnana, the desert volcano planet (red, fire, consciousness, tongue?)
	 is where the water bombs are useful.
	 there are hot lizards here.
** the screens
*** main screen
 four buttons: attack, jump, special, defend.
 there is a map on the top right.
*** map screen
 shows current position, save points, boss rooms.
*** item screen
 shows your items.


** ITEMS
 each item has a weight.

** Dungeon Rooms
  dungeon entrance.
  save room.
  boss room.
  empty room.
  monster room.
  secret room.
  trap room.
  treasure room.** World
  the character and the world are inseperable.

  the rooms are generated as soon as they are entered, then saved along
  with the game progress. so in this way, the world is endless but remains
  unique. there are themed rooms too and so it forms a heirarchy, not just
  of rooms but of themed areas. the map is a grid by screen size. 4:3.

  only if there are teleports: ?
  the whole dungeon is saved, so monsters do not come back. and breakable
  things stay broken if they were broken.

  monsters actually respond after 1 minute or so after being killed.

  there will need to be logic so that if a player needs an item to continue
  from getting stuck, they can somehow get it. say if they are surrounded
  with no health, by rooms that require health to pass, and another room
  that needs a certain item to cross lava (or something), then ..
