#+TITLE: Human Technology

* Spider

lol internet. let's dissect. di-sect.

"Spider webs found to attract insects by pulling them in using electric charge created by their own flapping wings"
web. insect = in sect, in sex, in cel, incel. in cells (sects).
electric. el(g-d) ek (?) trick. ..ect.. tri, ickt.

using their own "flapping wings" (gums). one's ego it-self lulls them in as how the web is 'programmed'.
insects dont randomly fly into things. they fall into the trap laid by her spinnerets.

el ek (?) trick city

huma sect?
huma's ECT? electro shock ??
induce seizures. get ppl off the web.
get computer running prayers not bitcoin. PRAY not PREY.
spider MAN!

insect does not "smell" information. it has ANTENNA which use "wireless communications" like our Wi-Fi tech.
boring machines made from worms.
most insects are sensitive to electrickal disturbances.


* Nuggets
Those who create from destruction, are indebted to this creation.
Those who destroy from creation, are indebted to this destruction.

* --- Starting Points ---
* Technology is Black Magic
we spend our light points to pull something in to our mind in enjoyment
or displeasure.

* The Internet
we are building this perfect endless artificial heaven and we are trying
to upload our best version of ourselves into it, for some kind of
immortality, but it is not going to work that way. no one else is
watching, its a hellish pit of soul traps. it is best to stay away from
investing too much into that place.

* The World
we are not trapped in this place. there is a way out, a way to fix
everything. and now we are following it, having gone too far the one
way (toward complexity)

* Outer Space
our scientific idea of space is the externally manifested vaccuous
singularity of infinity. it is the center of the world, and shrinking
our tech and celebs into it might not exactly help with understanding
what is actually going on.

* The Earth
it expands outward, as resolution/growth/time increases. gravity is
the push from the center. 'dinosaur' bones expand like sponges, the
fossiled objects of the dug past.

* Symmetry
Body moves, mind stays still.
Mind moves, body stays still.
The movements of body and mind are inversely reflective of each other.
Those who control the eyes control the mind.

* The Senses
There are six, but functionally three.
Sound and touch are one channel.
Sight and mind are a second channel.
Smell and taste are a third.

Lower sound frequencies are felt as touch, higher ones as well.
Smelling food or frangrance should be no different texture than that
of tasting.
When we think, we cannot see. When we are watching, we cannot think.

* The Body
sit straight. symmetry is very important.
so is the belly and the nose and the hands. very important.

* The Mind
dont lose it. follow the eyes. watch where you put it before it gets
too wild. elevate it upward and behind the body. everything in front;
and as our senses are prepared, their allocated directions.

* acting around other people
dont make so much noise; everyone has to hear it, and it only adds to
karmic debt. sound is the conflict of bodies trying to occupy the same
space. it taxes the system.

* network and processing
please be kind to other users and respect the equal opportunity for
processing time. try to keep your personal objects in your awareness,
and realise that simplofying our environment can be a great benefit to
mental clarity and sense of peace, which is essential for smooth
operation.

* scoring
one's rewards and punishments are appropriate to the benefit or
disruption to the system as a whole. we can all live together.

* 

